### ISSUE TITLE
Minagoroshi roadmap

### ISSUE THREAD

**Issue by enumag** [07th-mod/minagoroshi#1]
- [x] Commit vanilla scripts
- [x] Run Robomi
- [x] Manually insert missing PS3 voices
- [x] Solve known issues, use PS2 voices where possible
- [x] Combine `\n` lines
- [x] Voice pack
- [x] Spell check
- [x] Translate Katari images [mina_katari.zip](https://github.com/07th-mod/minagoroshi/files/3413446/mina_katari.zip)
- [x] PS3 Graphics
- [x] Flashback sprites and CGs
- [x] New UI
- [x] TipsPrefab
- [x] DLL update
- [x] New config sliders
- [x] ADV + LS update
- [x] CGAlt pack
- [x] Scenario screen
- [x] Text CGs
- [x] Tips screens
- [x] Bern's poem
- [x] Hanyuu's monologue
- [x] 07th-mod logo
- [x] New textbox
- [x] Insert PS3 opening
- [x] Update voice and bgm volumes
